Repository Say-Their-Name/say-their-names-ios, pull requests merged in 2020-06, with the labels that each got.

#11 [UI] Added Person details scene
  Say Their Names.xcodeproj/project.pbxproj
  Say Their Names/Resources/Assets.xcassets/Contents.json
  Say Their Names/Resources/Assets.xcassets/icons/Share Icon.imageset/Share Icon.png
  Say Their Names/Resources/Assets.xcassets/icons/Share Icon.imageset/Share Icon@2x.png
  Say Their Names/Resources/Assets.xcassets/icons/Share Icon.imageset/Share Icon@3x.png
  Say Their Names/Resources/Assets.xcassets/icons/arrow_left.imageset/Contents.json
  Say Their Names/Resources/Assets.xcassets/icons/arrow_left.imageset/Group 174.png
  Say Their Names/Resources/Assets.xcassets/icons/arrow_left.imageset/Group 174@2x.png
  Say Their Names/Resources/Assets.xcassets/icons/arrow_left.imageset/Group 174@3x.png
  Say Their Names/Resources/Assets.xcassets/icons/arrow_right.imageset/Arrow Icon.png
  Say Their Names/Resources/Assets.xcassets/icons/arrow_right.imageset/Arrow Icon@2x.png
  Say Their Names/Resources/Assets.xcassets/icons/arrow_right.imageset/Arrow Icon@3x.png
  Say Their Names/Resources/Assets.xcassets/icons/arrow_right.imageset/Contents.json
  Say Their Names/Resources/Assets.xcassets/icons/bookmark_active.imageset/Contents.json
  Say Their Names/Resources/Assets.xcassets/icons/bookmark_active.imageset/Path_507.png
  Say Their Names/Resources/Assets.xcassets/icons/bookmark_active.imageset/Path_507@2x.png
  Say Their Names/Resources/Assets.xcassets/icons/bookmark_active.imageset/Path_507@3x.png
  Say Their Names/Resources/Assets.xcassets/icons/edit_active.imageset/Contents.json
  Say Their Names/Resources/Assets.xcassets/icons/edit_active.imageset/Shape@2x.png
  Say Their Names/Resources/Assets.xcassets/icons/edit_active.imageset/Shape@3x-1.png
  Say Their Names/Resources/Assets.xcassets/icons/edit_active.imageset/Shape@3x.png
  Say Their Names/Resources/Assets.xcassets/icons/heart_active.imageset/Contents.json
  Say Their Names/Resources/Assets.xcassets/icons/heart_active.imageset/heart.png
  Say Their Names/Resources/Assets.xcassets/icons/heart_active.imageset/heart@2x.png
  Say Their Names/Resources/Assets.xcassets/icons/heart_active.imageset/heart@3x.png
  Say Their Names/Resources/Assets.xcassets/icons/share.imageset/Contents.json
  Say Their Names/Resources/Assets.xcassets/icons/share.imageset/image 1.png
  Say Their Names/Resources/Assets.xcassets/icons/share.imageset/image 1@2x.png
  Say Their Names/Resources/Assets.xcassets/icons/share.imageset/image 1@3x.png
  Say Their Names/Source/Components/MainTabBarController.swift
  Say Their Names/Source/Controller/Home/HomeController.swift
  Say Their Names/Source/Controller/Home/Person/PersonController.swift
  Say Their Names/Source/Controller/Home/Person/PersonController.xib
  Say Their Names/Source/Controller/Home/Person/PersonDetailsController.swift
  Say Their Names/Source/Controller/Home/Person/PersonDetailsController.xib
  Say Their Names/Source/View/Home/Person/PersonCell.xib
  Say Their Names/Source/View/Home/Person/PersonPhotoCell.swift
  Say Their Names/Source/View/Home/Person/PersonPhotoCell.xib
Labels: enhancement

#53 Fix linter warnings for forced unwrapping
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Service/DateFormatter/DateFormatterService.swift
  SayTheirNamesTests/DateFormatterServiceTest/DateFormatterServiceTests.swift
Labels: review me

#57 Add readme and contributing to the Xcode project
  SayTheirNames.xcodeproj/project.pbxproj
Labels: review me

#55 Use semantic font
  SayTheirNames/Source/Components/MainTabBarController.swift
Labels: review me

#65 Update README to remove the no longer relevant spaces
  README.md
Labels: review me

#63 Fixing the linter
  .github/workflows/swiftlint.yml
  .swiftlint.yml
Labels: review me

#61 Add Servicing protocol to define the behavior of the service
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Controller/Base/BaseViewController.swift
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionDetailViewController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
  SayTheirNames/Source/Service/Navigator/Navigator.swift
  SayTheirNames/Source/Service/Service.swift
  SayTheirNames/Source/Service/ServiceReferring.swift
Labels: review me

#62 Diffable data source on Home
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/AppDelegate.swift
  SayTheirNames/Source/Components/CustomSearchBar.swift
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/LocationCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/PersonCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Model/Location.swift
  SayTheirNames/Source/Model/Person.swift
  SayTheirNames/Source/Utils/Extentions/UICollectionReusableView+Reusable.swift
  SayTheirNames/Source/Utils/Extentions/UICollectionView++.swift
  SayTheirNames/Source/Utils/Extentions/UICollectionViewCell++.swift
  SayTheirNames/Source/View/Home/Location/LocationCell.swift
  SayTheirNames/Source/View/Home/Person/PersonHeaderCell.swift
  SayTheirNamesTests/DataSourceTests/LocationCollectionViewDataSourceTests.swift
Labels: being worked on

#77 Update CONTRIBUTING.md with FAQ
  CONTRIBUTING.md
Labels: review me

#71 improved Home View Controller layout in landscape mode
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/HomeView.swift
Labels: review me

#79 Added Portuguese Localization
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/pt-BR.lproj/Localizable.strings
Labels: review me

#82 changed to non-mutable
  SayTheirNames/Source/Model/Donation.swift
  SayTheirNames/Source/Model/Image.swift
  SayTheirNames/Source/Model/Link.swift
  SayTheirNames/Source/Model/Location.swift
  SayTheirNames/Source/Model/Media.swift
  SayTheirNames/Source/Model/Person.swift
  SayTheirNames/Source/Model/Petition.swift
  SayTheirNames/Source/Model/SocialMedia.swift
Labels: review me

#80 [Chore] Opt-in to trigger Object Literals as warnings in SwiftLint
  .swiftlint.yml
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Utils/Color/UIColor+Resource.swift
Labels: review me

#91 Add voice over support
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/LocationCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/PersonCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.xib
  SayTheirNames/Source/View/Home/Person/PersonCell.swift
  SayTheirNames/Source/View/Home/Person/PersonHeaderCell.xib
  SayTheirNames/Source/View/Home/Person/PersonPhotoCell.swift
  SayTheirNames/Source/View/Home/Search/SearchResultCell.xib
Labels: review me

#88 Person Controller - Programmatic UI
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Assets.xcassets/icons/news_bbc.imageset/Contents.json
  SayTheirNames/Resources/Assets.xcassets/icons/news_bbc.imageset/news_bbc.png
  SayTheirNames/Resources/Assets.xcassets/icons/news_bbc.imageset/news_bbc@2x.png
  SayTheirNames/Resources/Assets.xcassets/icons/news_bbc.imageset/news_bbc@3x.png
  SayTheirNames/Resources/Assets.xcassets/icons/share_dark.imageset/Contents.json
  SayTheirNames/Resources/Assets.xcassets/icons/share_dark.imageset/share_dark.png
  SayTheirNames/Resources/Assets.xcassets/icons/share_dark.imageset/share_dark@2x.png
  SayTheirNames/Resources/Assets.xcassets/icons/share_dark.imageset/share_dark@3x.png
  SayTheirNames/Resources/Assets.xcassets/icons/share_white.imageset/Contents.json
  SayTheirNames/Resources/Assets.xcassets/icons/share_white.imageset/share_white.png
  SayTheirNames/Resources/Assets.xcassets/icons/share_white.imageset/share_white@2x.png
  SayTheirNames/Resources/Assets.xcassets/icons/share_white.imageset/share_white@3x.png
  SayTheirNames/Resources/Assets.xcassets/stock/media-image-1.imageset/Contents.json
  SayTheirNames/Resources/Assets.xcassets/stock/media-image-1.imageset/media-image-1.png
  SayTheirNames/Resources/Assets.xcassets/stock/media-image-2.imageset/Contents.json
  SayTheirNames/Resources/Assets.xcassets/stock/media-image-2.imageset/man-wearing-yellow-jacket-1317712.jpg
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.xib
  SayTheirNames/Source/Controller/Home/Person/PersonDetailsController.swift
  SayTheirNames/Source/Controller/Home/Person/PersonDetailsController.xib
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
  SayTheirNames/Source/View/ButtonContainerView.swift
  SayTheirNames/Source/View/HashtagView.swift
  SayTheirNames/Source/View/ImageWithBlurView.swift
Labels: review me

#95 [CHORE] Update contribution description
  CONTRIBUTING.md
Labels: review me

#99 [FIX] Circular reference between Navigator & Service
  SayTheirNames/Source/SceneDelegate.swift
  SayTheirNames/Source/Service/Navigator/Navigator.swift
  SayTheirNames/Source/Service/Service.swift
Labels: review me

#100 [CHORE] Adds localization to PersonController.
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
Labels: review me

#97 [Chore] Remove BaseViewController and implement ServiceReferring
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Base/BaseViewController.swift
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Settings/SettingsController.swift
Labels: review me

#96 [UI] VoiceOver improvements for location bar
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/LocationCollectionViewDataSource.swift
  SayTheirNames/Source/Utils/Extentions/UICollectionView++.swift
  SayTheirNames/Source/View/Home/Location/LocationCell.swift
Labels: review me

#102 [CHORE] Add License copy into PersonController associated cells
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
Labels: review me

#103 [UI] person VoiceOver improvements
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
Labels: review me

#69 All programmatic UI views now support dynamic type
  .swiftlint.yml
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Home/HomeView.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
  SayTheirNames/Source/Controller/Petitions/PetitionDetailView.swift
  SayTheirNames/Source/Controller/Petitions/PetitionTableViewCell.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsView.swift
  SayTheirNames/Source/Utils/Extentions/UIFont++.swift
  SayTheirNames/Source/Utils/Fonts/UIFont+Resource.swift
  SayTheirNames/Source/View/ButtonContainerView.swift
  SayTheirNames/Source/View/HashtagView.swift
  SayTheirNames/Source/View/Home/Location/LocationCell.swift
  SayTheirNames/Source/View/Home/Person/PersonCell.swift
Labels: review me

#105 [CHORE] added icon
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/20@2x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/20@3x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/29@2x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/29@3x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/40@2x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/40@3x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/57@2x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/60@2x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/60@3x.png
  SayTheirNames/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: review me

#104 Fix Code of Conduct link in README.md
  README.md
Labels: review me

#89 [FEAT] Replace SettingsController with AboutController
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames.xcodeproj/project.pbxproj.orig
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Controller/More/AboutController.swift
  SayTheirNames/Source/Controller/More/AboutView.swift
  SayTheirNames/Source/Controller/Settings/SettingsController.xib
Labels: review me

#108 [CHORE] Use UIColor.STN extension
  SayTheirNames/Source/Components/CustomNavigationBar.swift
  SayTheirNames/Source/Components/CustomSearchBar.swift
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/HomeView.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
  SayTheirNames/Source/Controller/Petitions/PetitionDetailView.swift
  SayTheirNames/Source/Utils/Color/UIColor+Resource.swift
  SayTheirNames/Source/View/ButtonContainerView.swift
  SayTheirNames/Source/View/Common/STNNavigationBar.swift
  SayTheirNames/Source/View/ImageWithBlurView.swift
Labels: review me

#109 [Chore] Refactor filter category cell constraints
  SayTheirNames/Source/View/Filter/FilterCategoryCell.swift
Labels: review me

#85 [Chore] Add theme file
  CONTRIBUTING.md
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Components/CustomSearchBar.swift
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/HomeView.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonHashtagTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
  SayTheirNames/Source/Utils/Extentions/UIEdgeInsets+init.swift
  SayTheirNames/Source/Utils/Theme/Theme.swift
Labels: review me

#110 [BUG] - Fix auto-layout breaks & minor design detail
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCollectionView.swift
Labels: branch-out-of-date, review me

#111 [FEAT] Implement DonationsMoreDetailsController.
  .swiftlint.yml
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController+Layout.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDDonationButtonSupplementaryView.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDHashtagCell.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDPhotoSupplementaryView.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDSectionTitleSupplementaryView.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTextContentCell.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTitleCell.swift
  SayTheirNames/Source/View/ImageWithBlurView.swift
Labels: review me

#114 [CHORE] Fix fetch donations endpoint request
  SayTheirNames/Source/Components/CustomSearchBar.swift
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonOverviewTableViewCell.swift
  SayTheirNames/Source/Model/Donation.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
Labels: review me

#120 [CHORE] Update French localization file
  SayTheirNames/Resources/fr.lproj/Localizable.strings
Labels: enhancement

#112 [FEAT] Add Arabic localization
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Info.plist
  SayTheirNames/Resources/ar.lproj/Localizable.strings
Labels: branch-out-of-date

#117 Hide location filters for v1
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/HomeView.swift
  SayTheirNamesUITests/SayTheirNamesUITests.swift
Labels: review me

#121 [FEAT] Add Korean localization
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Resources/ko.lproj/Localizable.strings
Labels: branch-out-of-date, review me

#122 Remove custom navigation views and convert them to native
  SayTheirNames/Source/Components/CustomSearchBar.swift
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsView.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/HomeView.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsView.swift
Labels: merge me

#123 [CHORE] Refactor PetitionsController
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Donations/DonationsView.swift
  SayTheirNames/Source/Controller/Petitions/PetitionTableViewCell.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsCollectionViewManager.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsTableViewDataSource.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsView.swift
  SayTheirNames/Source/Model/Petition.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCollectionView.swift
Labels: review me

#124 [BUG] - Fix auto-layout issues with Filter
  SayTheirNames/Source/Controller/Donations/DonationsView.swift
  SayTheirNames/Source/Utils/Theme/Theme.swift
  SayTheirNames/Source/View/Filter/FiltersCollectionView.swift
Labels: review me

#125 Add MIT license as default header to every new file
  SayTheirNames.xcodeproj/xcshareddata/IDETemplateMacros.plist
Labels: review me

#126 [CHORE] - Add Person Details Networking
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Dependency/Networking/Requestors/PeopleNetworkRequestor.swift
  SayTheirNames/Source/Model/Person.swift
  SayTheirNamesTests/DataSourceTests/PersonCollectionViewDataSourceHelperTests.swift
Labels: review me

#127 [CHORE] Added more networking and modeling
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Dependency/DateFormatter/DateFormatterService.swift
  SayTheirNames/Source/Dependency/Networking/NetworkRequestor.swift
  SayTheirNames/Source/Dependency/Networking/Requestors/PeopleNetworkRequestor.swift
  SayTheirNames/Source/Model/Person.swift
  SayTheirNames/Source/View/Home/Person/PersonCell.swift
  SayTheirNamesTests/DataSourceTests/PersonCollectionViewDataSourceHelperTests.swift
  SayTheirNamesTests/DateFormatterServiceTest/DateFormatterServiceTests.swift
Labels: review me

#136 [CHORE] DonationsMoreDetailsController Localization Support
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDDonationButtonSupplementaryView.swift
Labels: build failed, good first issue

#132 [FEAT] Russian localisation support
  SayTheirNames/Resources/ru-RU.lproj/Localizable.strings
Labels: branch-out-of-date

#138 [CHORE] mapped AFError to Swift.Error
  SayTheirNames/Source/Dependency/Networking/NetworkRequestor.swift
  SayTheirNames/Source/Dependency/Networking/Requestors/DonationsNetworkRequestor.swift
  SayTheirNames/Source/Dependency/Networking/Requestors/PeopleNetworkRequestor.swift
  SayTheirNames/Source/Dependency/Networking/Requestors/PetitionsNetworkRequestor.swift
  SayTheirNames/Source/Dependency/Networking/Requestors/SearchNetworkRequestor.swift
  SayTheirNamesTests/ServiceTests/NetworkRequestorTests.swift
Labels: review me

#139 [FIX] Avoid showing "0" in labels if age or children count are null
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Model/Person.swift
Labels: review me

#140 [CHORE ]added a reusable result extension
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Dependency/Networking/NetworkRequestor.swift
  SayTheirNames/Source/Utils/Extentions/AFError+STN.swift
  SayTheirNames/Source/Utils/Extentions/Result+STN.swift
Labels: review me

#141 [CHORE] added useful resources section
  CONTRIBUTING.md
Labels: review me

#143 Fix missing launch asset in launch screen
  SayTheirNames/Resources/Base.lproj/LaunchScreen.storyboard
  SayTheirNames/Source/Controller/Launch/LaunchScreen.xib
  SayTheirNames/Source/View/HashtagView.swift
Labels: merge me, review me

#144 [CHORE] Remove Firebase config plist
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/GoogleService-Info.plist
Labels: merge me, review me

#131 [FEAT] Implement AboutController
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Controller/More/AboutView.swift
  SayTheirNames/Source/Controller/More/MoreCard.swift
  SayTheirNames/Source/Controller/More/MoreController.swift
  SayTheirNames/Source/Controller/More/MoreView.swift
  SayTheirNames/Source/Utils/Theme/Theme.swift
Labels: merge me, review me

#135 [Chore] adding extensions tests UIEdgeInsetsInitTests
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames.xcodeproj/project.pbxproj.orig
  SayTheirNames/Source/Utils/Extentions/UIEdgeInsets+init.swift
  SayTheirNamesTests/ExtensionsTests/UIEdgeInsetsInitTests.swift
Labels: merge me, test-cases

#148 [FEAT]: donations cell find-out-more button action added
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/View/CallToAction/CallToAction.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
Labels: review me

#133 [FEAT] Pagination on Home
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/PersonCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/HomeView.swift
  SayTheirNames/Source/FeatureFlags.swift
  SayTheirNames/Source/Model/Link.swift
  SayTheirNames/Source/Utils/Pagination/Paginator.swift
  SayTheirNamesTests/UtilsTests/PaginatorTests.swift
Labels: review me

#153 [CHORE] : Unit tests for Model
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames.xcodeproj/xcshareddata/xcschemes/SayTheirNames.xcscheme
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/Contents.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/donations.dataset/Contents.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/donations.dataset/donations.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/people.dataset/Contents.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/people.dataset/people.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/petitions.dataset/Contents.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/petitions.dataset/petitions.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/search.dataset/Contents.json
  SayTheirNamesTests/Model/JSONDataModelAPIs.xcassets/search.dataset/search.json
  SayTheirNamesTests/Model/ModelTests.swift
Labels: review me, test-cases

#171 [UI] Text tweaks
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Components/MainTabBarController.swift
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/More/MoreController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
Labels: review me

#164 [UI] Fix/enable find out more buttons
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionDetailView.swift
  SayTheirNames/Source/Controller/Petitions/PetitionDetailViewController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
  SayTheirNames/Source/Controller/Petitions/PresentedPetition.swift
Labels: review me

#173 [CHORE] Unit Tests for the Deep Linking mechanism.
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Dependency/Deep Linking/DeepLinkHandler.swift
  SayTheirNamesTests/ServiceTests/DeepLinkTests.swift
Labels: review me, test-cases

#175 Add MetadataService to load URL information
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
  SayTheirNames/Source/Dependency/DependencyContainer.swift
  SayTheirNames/Source/Dependency/MetadataService.swift
  SayTheirNames/Source/Model/News.swift
Labels: review me

#172 Hide image and tagView in donations and Petitions
  SayTheirNames/Source/FeatureFlags.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCollectionView.swift
Labels: review me

#179 [FIX] STN logo appears over text in donation details (dark mode only)
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
Labels: review me

#178 [BUGFEATURE] - #hashtags fixes + features on Person Details & Donation Details
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController+Layout.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTextContentCell.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Model/Donation.swift
  SayTheirNames/Source/Model/Hashtag.swift
  SayTheirNames/Source/Utils/Protocols/DynamicHeightCalculable.swift
  SayTheirNames/Source/Utils/Theme/Theme.swift
  SayTheirNames/Source/View/Hashtag/HashtagTableViewCell.swift
  SayTheirNames/Source/View/Hashtag/HashtagView.swift
  SayTheirNames/Source/View/Hashtag/HashtagViewCollectionViewCell.swift
Labels: review me

#180 [CHORE] Enable ViewController Based Status Bar Appearance
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Info.plist
  SayTheirNames/Source/Components/CustomNavigationController.swift
  SayTheirNames/Source/Components/MainTabBarController.swift
Labels: branch-out-of-date, review me

#182 [FIX] Reload lists
  SayTheirNames/Source/Components/CollectionViewManager/CollectionViewManager.swift
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/PersonCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
  SayTheirNamesTests/DataSourceTests/PersonCollectionViewDataSourceHelperTests.swift
Labels: review me

#184 [FEAT] Implement action on donate button on person and donation screens
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDPhotoSupplementaryView.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/View/ImageWithBlurView.swift
Labels: review me

#185 [CHORE] Finalise the More screen
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Resources/ar.lproj/Localizable.strings
  SayTheirNames/Resources/fr.lproj/Localizable.strings
  SayTheirNames/Resources/ko.lproj/Localizable.strings
  SayTheirNames/Resources/pt-BR.lproj/Localizable.strings
  SayTheirNames/Resources/ru-RU.lproj/Localizable.strings
  SayTheirNames/Source/Controller/More/MoreView.swift
  SayTheirNames/Source/Utils/Extentions/UIButton++.swift
Labels: review me

#189 [FEAT] Petition details (reusing donation details)
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTitleCell.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsController.swift
  SayTheirNames/Source/Model/Donation.swift
  SayTheirNames/Source/Model/Petition.swift
Labels: review me

#191 [UI] Make CTA button wider for Donation details screen
  SayTheirNames/Source/View/ButtonContainerView.swift
Labels: review me

#195 [CHORE] Remove .red and .yellow colors.
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Color.xcassets/red.colorset/Contents.json
  SayTheirNames/Resources/Color.xcassets/yellow.colorset/Contents.json
  SayTheirNames/Resources/Generated/assets.swift
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonPhotoTableViewCell.swift
  SayTheirNames/Source/Utils/Color/UIColor+Resource.swift
Labels: review me

#197 [BUG] Remove hardcoded string values
  SayTheirNames/Source/Controller/Home/Person/Views/PersonInfoTableViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsTableViewCell.swift
Labels: bug, review me

#193 [FIX] No extra spacing on hidden sections
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController+Layout.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTitleCell.swift
Labels: review me

#199 Deleted unused files
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Petitions/PetitionDetailView.swift
  SayTheirNames/Source/Controller/Petitions/PetitionDetailViewController.swift
Labels: review me

#200 [L10N] Localizing sign text
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Resources/ar.lproj/Localizable.strings
  SayTheirNames/Resources/en.lproj/Localizable.strings
  SayTheirNames/Resources/fr.lproj/Localizable.strings
  SayTheirNames/Resources/ko.lproj/Localizable.strings
  SayTheirNames/Resources/pt-BR.lproj/Localizable.strings
  SayTheirNames/Resources/ru.lproj/Localizable.strings
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
Labels: review me

#201 [FIX] Implement dynamic type on donations detail
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController+Layout.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDSectionTitleSupplementaryView.swift
  SayTheirNames/Source/Utils/Fonts/UIFont+Resource.swift
Labels: review me

#202 [CHORE] Update Deeplink for new host and scheme
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Info.plist
  SayTheirNames/Source/Dependency/DeepLinking/Deep Links/AboutDeepLink.swift
  SayTheirNames/Source/Dependency/DeepLinking/Deep Links/DonationsDeepLink.swift
  SayTheirNames/Source/Dependency/DeepLinking/Deep Links/HomeDeepLink.swift
  SayTheirNames/Source/Dependency/DeepLinking/Deep Links/PersonDeepLink.swift
  SayTheirNames/Source/Dependency/DeepLinking/Deep Links/PetitionsDeepLink.swift
  SayTheirNames/Source/Dependency/DeepLinking/DeepLink.swift
  SayTheirNames/Source/Dependency/DeepLinking/DeepLinkDetails.swift
  SayTheirNames/Source/Dependency/DeepLinking/DeepLinkHandler.swift
  SayTheirNames/Source/Dependency/DeepLinking/DeepLinkSupport.swift
Labels: review me

#203 [CHORE] Fixed Nav and Tab Bar Title Size
  SayTheirNames/Source/Utils/Fonts/UIFont+Resource.swift
Labels: review me

#204 [CHORE] Change print to Log.print
  SayTheirNames/Source/Controller/Donations/DonationsController.swift
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/Carousel/LineCarouselControl.swift
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/PersonCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsCollectionViewCell.swift
  SayTheirNames/Source/Controller/Launch/LaunchScreen.swift
  SayTheirNames/Source/Log/Log.swift
  SayTheirNames/Source/Utils/Extentions/UIFont+STN.swift
Labels: review me

#207 [UI] Fixing UI around donations
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DMDCollectionViewDataSource.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController+Layout.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDSectionTitleSupplementaryView.swift
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTitleCell.swift
  SayTheirNames/Source/Utils/Fonts/UIFont+Resource.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCollectionView.swift
Labels: review me

#209 [BUG] - Fix issue where cells would display the wrong information
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/View/DMDTextContentCell.swift
  SayTheirNames/Source/Controller/Home/CollectionViewDataSource/Carousel/CarouselCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
  SayTheirNames/Source/View/Hashtag/HashtagViewCollectionViewCell.swift
  SayTheirNames/Source/View/Home/Person/PersonCell.swift
Labels: review me

#210 [UI] Pass URL from Sharable to UIActivityVC to improve UX
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/Controller/Home/Person/PersonController.swift
  SayTheirNames/Source/Dependency/ShareService.swift
Labels: review me

#212 [CHORE] Delete code
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Donations/DonationsMoreDetails/DonationsMoreDetailsController.swift
  SayTheirNames/Source/View/Home/Person/PersonHeaderCell.xib
  SayTheirNames/Source/View/Home/Person/PersonPhotoCell.swift
Labels: review me

#213 [FIX] Handle nil image urls in cells
  SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
  SayTheirNames/Source/Utils/Extentions/UIImageView+STN.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
  SayTheirNames/Source/View/Home/Person/PersonCell.swift
  SayTheirNames/Source/View/ImageWithBlurView.swift
Labels: review me

#214 [CHORE] L10n update for FR
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/Generated/strings.swift
  SayTheirNames/Resources/ar.lproj/Localizable.strings
  SayTheirNames/Resources/en.lproj/Localizable.strings
  SayTheirNames/Resources/fr.lproj/Localizable.strings
  SayTheirNames/Resources/ko.lproj/Localizable.strings
  SayTheirNames/Resources/nl.lproj/Localizable.strings
  SayTheirNames/Resources/pt-BR.lproj/Localizable.strings
  SayTheirNames/Resources/ru.lproj/Localizable.strings
Labels: review me

#215 [FIX] Disable ko & pt-BR locales
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Resources/Base.lproj/Localizable.strings
  SayTheirNames/Resources/ar.lproj/Localizable.strings
  SayTheirNames/Resources/en.lproj/Localizable.strings
  SayTheirNames/Resources/fr.lproj/Localizable.strings
  SayTheirNames/Resources/ko.lproj/Localizable.strings
  SayTheirNames/Resources/nl.lproj/Localizable.strings
  SayTheirNames/Resources/pt-BR.lproj/Localizable.strings
  SayTheirNames/Resources/ru.lproj/Localizable.strings
  SayTheirNames/Source/Dependency/Networking/Environment.swift
Labels: review me

#216 [UI] Add trailing padding for about section
  SayTheirNames/Source/Controller/More/MoreView.swift
Labels: review me

#217 [UI] Enable images on donations and petitions
  SayTheirNames/Source/FeatureFlags.swift
Labels: review me

#220 [UI] BackgroundColor to resolve to SystemBackground, update usages for consistency.
  SayTheirNames/Resources/Color.xcassets/background.colorset/Contents.json
  SayTheirNames/Source/Controller/Donations/DonationsView.swift
  SayTheirNames/Source/Controller/Home/HomeController.swift
  SayTheirNames/Source/Controller/Home/HomeView.swift
  SayTheirNames/Source/Controller/Launch/LaunchScreen.swift
  SayTheirNames/Source/Controller/Petitions/PetitionsView.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCollectionView.swift
  SayTheirNames/Source/View/CallToAction/TagView.swift
  SayTheirNames/Source/View/Common/STNNavigationBar.swift
  SayTheirNames/Source/View/Filter/FiltersCollectionView.swift
Labels: review me

#221 [CHORE] Remove unused code
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Components/CustomNavigationBar.swift
  SayTheirNames/Source/Dependency/ImageDownloader/AsyncOperation.swift
  SayTheirNames/Source/Dependency/ImageDownloader/DownloadOperation.swift
  SayTheirNames/Source/Dependency/ImageDownloader/FileDataProvider.swift
  SayTheirNames/Source/Dependency/ImageDownloader/FileDownloader.swift
  SayTheirNames/Source/Dependency/ImageDownloader/ImageCache.swift
  SayTheirNames/Source/Dependency/ImageDownloader/ImageCreationOperation.swift
  SayTheirNames/Source/Dependency/ImageDownloader/ImageProvider.swift
  SayTheirNames/Source/Dependency/ImageDownloader/ImageService.swift
  SayTheirNames/Source/View/Common/STNNavigationBar.swift
Labels: review me

#222 [CHORE] Gather SDWebImage usage under ImageService
  SayTheirNames.xcodeproj/project.pbxproj
  SayTheirNames/Source/Controller/Home/Person/Views/PersonMediaCollectionViewCell.swift
  SayTheirNames/Source/Controller/Home/Person/Views/PersonNewsCollectionViewCell.swift
  SayTheirNames/Source/Dependency/DependencyContainer.swift
  SayTheirNames/Source/Dependency/ImageService+MetadataService.swift
  SayTheirNames/Source/Dependency/ImageService.swift
  SayTheirNames/Source/Dependency/MetadataService.swift
  SayTheirNames/Source/View/CallToAction/CallToActionCell.swift
  SayTheirNames/Source/View/Home/Person/PersonCell.swift
  SayTheirNames/Source/View/ImageWithBlurView.swift
Labels: review me
